name: 'Dart Pull Request Use Case Validator'
description: 'Validates your use cases to have valid class names and methods.'
branding:
   icon: search
   color: white
inputs:
   github-token:
     description: 'GitHub Access Token'
     default: ${{ github.token }}
     required: true
   method-name:
     description: 'Desired public callable method of a use case.'
     required: false
     default: 'run'
   approve-message:
     description: 'The message that is printed in the approve review message.'
     required: false
     default: 'The use cases for this pull requests were implemented correctly! Good job 👍'
outputs:
runs:
  using: 'node16'
  main: 'index.js'
